force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>A city, defined as a geographically governed region located within a county.</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>A country, defined as a geographical region that is identified as a distinct national entity.</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>A county, defined as an administrative region of a state or province.</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Counties</relationshipLabel>
    <relationshipName>Counties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>A state or province, a type of political subdivision of a country.</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StateCountryCityCountyController.cls
public with sharing class StateCountryCityCountyController {
    @AuraEnabled
    public static List<Country__c> getCountries() {
        List<Country__c> countries = [SELECT Id, Name FROM Country__c];
        
        return countries;
    }

    @AuraEnabled
    public static List<State__c> getStates(Id countryId) {
        // Find all states looking up to this country
        List<State__c> states = [SELECT Id, Name FROM State__c WHERE Country__c = :countryId];

        return states;
    }

    @AuraEnabled
    public static List<City__c> getCities(Id stateId) {
        // Find all states looking up to this country
        List<City__c> cities = [SELECT Id, County__c, Name FROM City__c WHERE State__c = :stateId];

        return cities;
    }

    @AuraEnabled
    public static List<County__c> getCounty(Id countyId) {
        List<County__c> county = [SELECT Id, Name FROM County__c WHERE Id = :countyId];
        
        System.debug(county);

        return county;
    }
}